### ISSUE TITLE
"undefined method `command_with_shell'" after upgrading to v1.4.2 (on Engine Yard Managed)

### ISSUE THREAD

**Issue by baburdick** [wayneeseguin/rvm-capistrano#82]
- https://github.com/engineyard/eycap/blob/master/lib/eycap/recipes/rvm.rb#L16
- https://github.com/engineyard/eycap/blob/master/lib/eycap/recipes/bundler.rb#L11

```
$ cap staging deploy
[...SNIP...]
undefined method `command_with_shell' for #<Capistrano::Configuration::Namespaces::Namespace:0x007fe89c04c630>
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:193:in `method_missing'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/eycap-0.6.8/lib/eycap/recipes/bundler.rb:11:in `block (4 levels) in <top (required)>'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/invocation.rb:78:in `block in parallel'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/command.rb:107:in `initialize'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/invocation.rb:78:in `new'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/invocation.rb:78:in `parallel'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/eycap-0.6.8/lib/eycap/recipes/bundler.rb:8:in `block (3 levels) in <top (required)>'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/callback.rb:38:in `call'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/callback.rb:38:in `call'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:254:in `block (2 levels) in load'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:234:in `block (3 levels) in load'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:56:in `transaction'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:233:in `block (2 levels) in load'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:201:in `block (2 levels) in load'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `each'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:34:in `execute!'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
~/.rvm/gems/ruby-1.9.3-p429@app/bin/cap:19:in `load'
~/.rvm/gems/ruby-1.9.3-p429@app/bin/cap:19:in `<main>'
~/.rvm/gems/ruby-1.9.3-p429@app/bin/ruby_noexec_wrapper:14:in `eval'
~/.rvm/gems/ruby-1.9.3-p429@app/bin/ruby_noexec_wrapper:14:in `<main>'
```

Attempted to fix per @mpapis with this block after `require "rvm/capistrano"` in `config/deploy.rb`:

``` ruby
module Capistrano
  class Configuration
    module Namespaces
      class Namespace
        include Capistrano::RvmMethods
      end
    end
  end
end
```

... but apparently eycap v0.6.8 thwarts this (see links above):

```
$ cap staging deploy
[...SNIP...]
./config/deploy.rb:11:in `<class:Namespace>': uninitialized constant #<Class:0x007fcd419c9350>::Capistrano::RvmMethods (NameError)
  from ./config/deploy.rb:10:in `<module:Namespaces>'
    from ./config/deploy.rb:9:in `<class:Configuration>'
    from ./config/deploy.rb:8:in `<module:Capistrano>'
    from ./config/deploy.rb:7:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:93:in `instance_eval'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:93:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:180:in `load_from_file'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:89:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `block in load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `each'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `load'
    from Capfile:8:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:93:in `instance_eval'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:93:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:180:in `load_from_file'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:89:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `block in load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `each'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/configuration/loading.rb:86:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:65:in `block in load_recipes'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:65:in `each'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:65:in `load_recipes'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:31:in `execute!'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/bin/cap:19:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/bin/cap:19:in `<main>'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/bin/ruby_noexec_wrapper:14:in `eval'
    from ~/.rvm/gems/ruby-1.9.3-p429@app/bin/ruby_noexec_wrapper:14:in `<main>'
```
